# Generated by Django 4.2.14 on 2025-01-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
